### ISSUE TITLE
SyntaxError: invalid syntax in krige.py

### ISSUE THREAD

**Issue by tmuehlen80** [capaulson/pyKriging#29]
Hello all,
when trying to run pyKriging the first time, I got the following error on import:

  File "C:\Users\xxxxx\Anaconda3\lib\site-packages\pyKriging\krige.py", line 142
    except Exception, err:
                    ^
SyntaxError: invalid syntax

I am running a Jupyter notebook using python 3.6.1. My pyKriging version is 0.1.0, installed via pip. Is there another version of pyKriging to be used?

**Comment by capaulson** [comment]
I need to update the pip version. Try pulling the master from github to install. Let me know if you have any more problems.

**Comment by ymyang0611** [comment]
Hello ，
Has the problem been solved?
I had the same problem when i trying run demo in introduction yesterday

File "C:\Users\xxxxx\Anaconda3\lib\site-packages\pyKriging\krige.py", line 142
except Exception, err:
^
SyntaxError: invalid syntax

**Comment by capaulson** [comment]
@ymyang0611 This is using the version on pip? Can you try installing using the latest Github source? Does the problem still exist?

**Comment by ymyang0611** [comment]
@capaulson  if i install module using the latest Github source，The following error is prompted：
Traceback (most recent call last):
  File "E:/Code/PyCode/TEMP.py", line 1, in <module>
    import pyKriging
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\pykriging-0.1.0-py3.5.egg\pyKriging\__init__.py", line 2, in <module>
    from .krige import *
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\pykriging-0.1.0-py3.5.egg\pyKriging\krige.py", line 6, in <module>
    from scipy.optimize import minimize
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\optimize\__init__.py", line 240, in <module>
    from .optimize import *
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2

**Comment by capaulson** [comment]
Ok, well that's good news. This now has issues with scipy. Which version of Scipy are you using? 

On python3.5 on ubuntu, I get:

**Comment by capaulson** [comment]
Closing because no additional information was provided.
